# Generated by Django 4.1.5 on 2023-01-29 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressee', '0002_alter_addressee_operator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressee',
            name='operator_code',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
