# Generated by Django 4.1.5 on 2023-01-29 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('type', models.IntegerField(choices=[(0, 'regular'), (1, 'once')], default=1)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('stop_at', models.DateTimeField(default=None, null=True)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addressee.addressee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.scheduledevent')),
            ],
        ),
    ]
