# Generated by Django 4.1.5 on 2023-01-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('type', models.IntegerField(choices=[(0, 'regular'), (1, 'once')], default=1)),
                ('start_at', models.DateTimeField(null=True)),
                ('stop_at', models.DateTimeField(default=None, null=True)),
                ('text', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='status',
            field=models.IntegerField(choices=[(100, 'unknown'), (200, 'done'), (300, 'reserved'), (400, 'failed')], default=100),
        ),
        migrations.AddIndex(
            model_name='messagingevent',
            index=models.Index(fields=['start_at', 'stop_at'], name='messaging_m_start_a_5eafba_idx'),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='messaging.messagingevent'),
        ),
        migrations.DeleteModel(
            name='ScheduledEvent',
        ),
    ]
