# Generated by Django 4.1.5 on 2023-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_scheduledmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmessage',
            name='status',
            field=models.IntegerField(choices=[(0, 'scheduled'), (100, 'processing'), (200, 'done'), (400, 'failed'), (500, 'unknown')], default=0),
        ),
    ]
