
# Generated by Django 4.1.5 on 2023-01-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_scheduledmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmessage',
            name='updated_by_task',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
