# Generated by Django 4.1.5 on 2023-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_create_sql_view_processing_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=512)),
                ('stop_at', models.DateTimeField(default=None, null=True)),
                ('text', models.CharField(max_length=512)),
                ('status', models.IntegerField(choices=[(100, 'scheduled'), (200, 'failed'), (300, 'processing'), (400, 'success'), (500, 'blocked')], default=100)),
                ('phone_number', models.BigIntegerField()),
                ('updated_by_task', models.UUIDField(default=None, null=True)),
            ],
            options={
                'db_table': 'active_messages',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=512)),
                ('stop_at', models.DateTimeField(default=None, null=True)),
                ('text', models.CharField(max_length=512)),
                ('status', models.IntegerField(choices=[(100, 'scheduled'), (200, 'failed'), (300, 'processing'), (400, 'success'), (500, 'blocked')], default=100)),
                ('phone_number', models.BigIntegerField()),
                ('updated_by_task', models.UUIDField(default=None, null=True)),
            ],
            options={
                'db_table': 'processing_messages',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
