# Generated by Django 4.1.5 on 2023-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_messagingevent_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingevent',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
