# Generated by Django 4.1.5 on 2023-01-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_messagingevent_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagingevent',
            name='type',
        ),
    ]
