# Generated by Django 4.1.5 on 2023-01-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_messagetext_remove_messagingevent_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingevent',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messagetext'),
        )
    ]
