# Generated by Django 4.1.5 on 2023-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='name',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
